all:
	g++ -std=c++11 -o program program.cpp
test00:
	./program <"input00.txt"> output00.txt
test01:
	./program <"input01.txt"> output01.txt
test02:
	./program <"input00.txt"> output02.txt
test03:
	./program <"input01.txt"> output03.txt
test04:
	./program <"input01.txt"> output04.txt
test05:
	./program <"input01.txt"> output05.txt
clean:
	rm program output*.txt